theme = "gruvbox_dark_soft"

[editor]
line-number = "relative"
cursorline = true  # Highlight the main cursor's line
rulers = [80, 100]
bufferline = "multiple"  # Display in-use buffers when there are multiple
trim-trailing-whitespace = true
trim-final-newlines = true

[editor.statusline]
left = ["mode", "spinner", "spacer", "version-control"]
center = ["file-name", "read-only-indicator", "file-modification-indicator"]
right = ["diagnostics", "selections", "register", "spacer", "position", "position-percentage", "spacer", "file-encoding", "file-line-ending"]
separator = "|"

[editor.lsp]
display-inlay-hints = false

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "block"

[editor.whitespace.render]
space = "all"
tab = "all"
[editor.whitespace.characters]
tabpad = " "  # Disable tab padding

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true

[editor.inline-diagnostics]
cursor-line = "warning"  # Display inline diagnostics on the current cursor's line
