theme = "catppuccin_mocha"

[editor]
line-number = "relative"
cursorline = true  # Highlight the main cursor's line
rulers = [80, 100]
bufferline = "multiple"  # Display in-use buffers when there are multiple
trim-trailing-whitespace = true
trim-final-newlines = true
